import { RouteInfo } from './sidebar.metadata';

export const ROUTES: RouteInfo[] = [
  {
    path: 'dashboard',
    title: 'DASHBOARD',
    icon: 'layers',
    class: '',
    groupTitle: false,
    claims: ['DASHBOARD_VIEW_DASHBOARD'],
    submenu: [],
  },
  {
    path: '',
    title: 'ASSIGNED_DOCUMENTS',
    icon: 'list',
    class: '',
    groupTitle: false,
    claims: [],
    submenu: [],
  },
  {
    path: 'documents',
    title: 'ALL_DOCUMENTS',
    icon: 'file-text',
    class: '',
    groupTitle: false,
    claims: ['ALL_DOCUMENTS_VIEW_DOCUMENTS'],
    submenu: [],
  },
  {
    path: 'documents/deep-search',
    title: 'DEEP_SEARCH',
    icon: 'zoom-in',
    class: '',
    groupTitle: false,
    claims: ['DEEP_SEARCH_DEEP_SEARCH'],
    submenu: [],
  },
  {
    path: '',
    title: 'AI_DOCUMENTS',
    icon: 'cpu',
    class: 'menu-toggle',
    groupTitle: false,
    claims: ['GENERATE_AI_DOCUMENTS', 'MANAGE_AI_PROMPT_TEMPLATES', 'VIEW_AI_GENERATED_DOCUMENTS'],
    submenu: [
      {
        path: 'ai-document-generator',
        title: 'AI_DOCUMENT_GENERATOR',
        icon: 'cpu',
        class: 'ml-menu',
        groupTitle: false,
        claims: ['GENERATE_AI_DOCUMENTS'],
        submenu: [],
      },
      {
        path: 'ai-document-generator-list',
        title: 'AI_DOCUMENT_LIST',
        icon: 'cpu',
        class: 'ml-menu',
        groupTitle: false,
        claims: ['VIEW_AI_GENERATED_DOCUMENTS'],
        submenu: [],
      }, {
        path: 'ai-template',
        title: 'AI_PROMPT_TEMPLATES',
        icon: 'email',
        class: 'ml-menu',
        groupTitle: false,
        claims: ['MANAGE_AI_PROMPT_TEMPLATES'],
        submenu: [],
      }
    ],
  },
  {
    path: 'bulk-document-upload',
    title: 'BULK_DOCUMENT_UPLOAD',
    icon: 'upload',
    class: '',
    groupTitle: false,
    claims: ['BULK_DOCUMENT_UPLOAD'],
    submenu: [],
  },
  {
    path: 'document-audit-trails',
    title: 'DOCUMENTS_AUDIT_TRAIL',
    icon: 'activity',
    class: '',
    groupTitle: false,
    claims: ['DOCUMENT_AUDIT_TRAIL_VIEW_DOCUMENT_AUDIT_TRAIL'],
    submenu: [],
  },
  {
    path: 'file-request',
    title: 'FILE_REQUEST',
    icon: 'inbox',
    class: '',
    groupTitle: false,
    claims: ['FILE_REQUEST_VIEW_FILE_REQUEST'],
    submenu: [],
  },
  {
    path: 'current-workflow',
    title: 'MY_WORKFLOWS',
    icon: 'git-merge',
    class: '',
    submenu: [],
    groupTitle: false,
    claims: ['WORKFLOW_VIEW_MY_WORKFLOWS'],
  },
  {
    path: '',
    title: 'WORKFLOWS',
    icon: 'activity',
    class: 'menu-toggle',
    groupTitle: false,
    claims: ['WORKFLOW_VIEW_WORKFLOW_SETTINGS', 'WORKFLOW_VIEW_ALL_WORKFLOWS', 'WORKFLOW_VIEW_WORKFLOW_LOGS'],
    submenu: [
      {
        path: 'workflow-settings',
        title: 'WORKFLOW_SETTINGS',
        icon: 'key',
        class: 'ml-menu',
        submenu: [],
        groupTitle: false,
        claims: ['WORKFLOW_VIEW_WORKFLOW_SETTINGS'],
      },
      {
        path: 'workflows',
        title: 'All_WORKFLOWS',
        icon: 'key',
        class: 'ml-menu',
        submenu: [],
        groupTitle: false,
        claims: ['WORKFLOW_VIEW_ALL_WORKFLOWS'],
      },
      {
        path: 'workflow-logs',
        title: 'WORKFLOW_LOGS',
        icon: 'key',
        class: 'ml-menu',
        submenu: [],
        groupTitle: false,
        claims: ['WORKFLOW_VIEW_WORKFLOW_LOGS'],
      },
    ],
  },
  {
    path: 'categories',
    title: 'DOCUMENT_CATEGORIES',
    icon: 'file',
    class: '',
    groupTitle: false,
    claims: ['DOCUMENT_CATEGORY_MANAGE_DOCUMENT_CATEGORY'],
    submenu: [],
  },
  {
    path: 'document-status',
    title: 'DOCUMENT_STATUS',
    icon: 'check',
    class: '',
    groupTitle: false,
    submenu: [],
    claims: ['MANAGE_DOCUMENT_STATUS']
  },
  {
    path: 'client',
    title: 'CLIENTS',
    icon: 'users',
    class: '',
    groupTitle: false,
    claims: ['CLIENTS_MANAGE_CLIENTS'],
    submenu: [],
  },
  {
    path: 'archived-documents',
    title: 'ARCHIVED_DOCUMENTS',
    icon: 'archive',
    class: '',
    groupTitle: false,
    claims: ['ARCHIVE_DOCUMENT_VIEW_DOCUMENTS'],
    submenu: [],
  },
  {
    path: 'expired-documents',
    title: 'EXPIRED_DOCUMENTS',
    icon: 'clock',
    class: '',
    groupTitle: false,
    claims: ['EXPIRED_DOCUMENTS_VIEW_DOCUMENT'],
    submenu: [],
  },
  {
    path: 'roles',
    title: 'ROLES',
    icon: 'users',
    class: '',
    groupTitle: false,
    claims: ['ROLE_VIEW_ROLES'],
    submenu: [],
  },
  {
    path: 'users',
    title: 'USERS',
    icon: 'user',
    class: '',
    groupTitle: false,
    claims: ['USER_VIEW_USERS'],
    submenu: [],
  },
  {
    path: 'roles/users',
    title: 'ROLE_USER',
    icon: 'user-check',
    class: '',
    groupTitle: false,
    claims: ['USER_ASSIGN_USER_ROLE'],
    submenu: [],
  },
  {
    path: 'reminders',
    title: 'REMINDER',
    icon: 'bell',
    class: '',
    groupTitle: false,
    claims: ['REMINDER_VIEW_REMINDERS'],
    submenu: [],
  },
  {
    path: '',
    title: 'LOGS',
    icon: 'log-in',
    class: 'menu-toggle',
    groupTitle: false,
    claims: ['LOGIN_AUDIT_VIEW_LOGIN_AUDIT_LOGS', 'LOGS_VIEW_CRON_JOBS_LOGS', 'LOGS_VIEW_EMAIL_LOGS'],
    submenu: [
      {
        path: 'login-audit',
        title: 'LOGIN_AUDITS',
        icon: 'target',
        class: 'ml-menu',
        groupTitle: false,
        claims: ['LOGIN_AUDIT_VIEW_LOGIN_AUDIT_LOGS'],
        submenu: [],
      }, {
        path: 'cron-job-logs',
        title: 'CRON_JOB_LOGS',
        icon: 'target',
        class: 'ml-menu',
        groupTitle: false,
        submenu: [],
        claims: ['LOGS_VIEW_CRON_JOBS_LOGS'],
      },
      {
        path: 'email-logs',
        title: 'EMAIL_LOGS',
        icon: 'target',
        class: 'ml-menu',
        groupTitle: false,
        submenu: [],
        claims: ['LOGS_VIEW_EMAIL_LOGS'],
      }
    ],
  },
  {
    path: '',
    title: 'SETTINGS',
    icon: 'settings',
    class: 'menu-toggle',
    groupTitle: false,
    claims: [
      'EMAIL_MANAGE_SMTP_SETTINGS',
      'SETTING_MANAGE_PROFILE',
      'SETTING_MANAGE_LANGUAGE',
      'SETTINGS_STORAGE_SETTINGS',
      'PAGE_HELPER_MANAGE_PAGE_HELPER',
      'SETTINGS_MANAGE_ALLOW_FILE_EXTENSIONS'
    ],
    submenu: [
      {
        path: 'email-smtp',
        title: 'SMTP_SETTING',
        icon: 'mail',
        class: 'ml-menu',
        groupTitle: false,
        claims: ['EMAIL_MANAGE_SMTP_SETTINGS'],
        submenu: [],
      },
      {
        path: 'company-profile',
        title: 'COMPANY_PROFILE',
        icon: 'mail',
        class: 'ml-menu',
        groupTitle: false,
        claims: ['SETTING_MANAGE_PROFILE', 'SETTINGS_STORAGE_SETTINGS', 'SETTINGS_MANAGE_OPEN_AI_API_KEY', 'SETTINGS_CHANGE_PDF_SETTINGS'],
        submenu: [],
      },
      {
        path: 'allow-file-extension',
        title: 'ALLOW_FILE_EXTENSIONS',
        icon: 'mail',
        class: 'ml-menu',
        groupTitle: false,
        claims: ['SETTINGS_MANAGE_ALLOW_FILE_EXTENSIONS'],
        submenu: [],
      },
      {
        path: 'languages',
        title: 'LANGUAGES',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        submenu: [],
        claims: ['SETTING_MANAGE_LANGUAGE'],
      },
      {
        path: 'page-helper',
        title: 'PAGE_HELPER',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        submenu: [],
        claims: ['PAGE_HELPER_MANAGE_PAGE_HELPER'],
      }
    ],
  },
];
